name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
    
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Iniciando Login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Fin del login"
          echo "New Version: $NEW_VERSION !!!"

      # - name: Build Docker Image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USER }}/docker-graphql:${{ steps.version.outputs.version }} .
      #     docker build -t ${{ secrets.DOCKER_USER }}/docker-graphql:latest .

      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ secrets.DOCKER_USER }}/docker-graphql:${{ steps.version.outputs.version }}
      #     docker push ${{ secrets.DOCKER_USER }}/docker-graphql:latest
